### ISSUE TITLE
Disable Editable Input (Feature request)

### ISSUE THREAD

**Issue by kkrishnan90** [himelbrand/react-native-numeric-input#1]
Hi, 
Thanks for such an awesome library ! Really appreciate it !
I would like to know how do I disable the editable part of the input between the two selector buttons.
I tried applying a style ```inputStyle={{editable:false}}``` as a prop to the ```Numeric Input``` component. But doesn't seem work. 

Awaiting your response. Thanks in advance !

**Comment by himelbrand** [comment]
@kkrishnan90 hello,
I just added support for the editable prop,
it was added to the docs as well.
it will be available from version 1.2.0
the editable prop is a boolean prop, with a default value of true

thank you for bringing it to my attention
