### ISSUE TITLE
On decimal input . removed

### ISSUE THREAD

**Issue by bvanleeuwen1995** [himelbrand/react-native-numeric-input#14]
When I enter the decimal sign on my keyboard it gets automatically removed so I can never enter a decimal value only when using steps.

**Comment by himelbrand** [comment]
@bvanleeuwen1995 I just fixed the Example and I see no problem, 
checkout this video of the example app, you can look at the source code if it helps.
![ezgif-5-7c6e06f3ebdf](https://user-images.githubusercontent.com/19415789/47613523-69855f80-da99-11e8-8f5d-2fd71af60984.gif)

**Comment by bvanleeuwen1995** [comment]
Correct, on iOS it works like it should, however on our Samsung Galaxy S6,S7 and S9 it doesn't work correctly.
