### ISSUE TITLE
when using with flat list

### ISSUE THREAD

**Issue by rahmatputrawiranata** [himelbrand/react-native-numeric-input#17]
when using with flatlist it throw to decimal then get max value 

![image](https://user-images.githubusercontent.com/34281063/48511724-1d546080-e88a-11e8-8ae2-7be4dd70ac07.png)

constructor(props) {
        super(props)
            this.state = {
                v3: 0,
            }
    }
    renderItem = ({item}) => {
        if(item.quota === 0){
            return(
                <Text>sorry abis bos</Text>
            )
        }
        return(
            <View>
               <View>
                   <Image 
                       style={{width : 80, height: 80}}
                       source={{uri: item.image}}
                   />
               </View>
               <View>
                   <Text>{item.name}</Text>
                   <Text>Rp {item.price}</Text>
                   <View>
                       <Text>jumlah</Text>
                       <NumericInput initValue={this.state.v3}
                            value={this.state.v3}
                            onChange={(v3) => this.setState({ v3 })} rounded minValue={0} valueType='integer'/>
                   </View>
               </View>
               <View>
                   <Button
                        title='Beli Sekarang'
                    />
                    <Button
                        title='Tambahkan Ke keranjang'
                    />
               </View>
            </View>
        )
    }

**Comment by himelbrand** [comment]
can you upload the code in a more readable fashion, please? so I can try and help

**Comment by himelbrand** [comment]
closed, fixed in the latest version: 1.6.3
if still, this problem occurs, open a new issue.
