### ISSUE TITLE
Numeric input on Android

### ISSUE THREAD

**Issue by bvanleeuwen1995** [himelbrand/react-native-numeric-input#19]
I created #14 a couple of days ago, it was closed right away since it worked on iOS in simulator, while I can confirm this works great it is still broken on Android.

Every time I press the decimal sign on the keyboard it removed it straight away, I believe this is due to the casting from string that takes place inside the onChange function.

**Comment by himelbrand** [comment]
@bvanleeuwen1995  thanks for notifying me.
I'll fix it as soon as possible if you have a fix you're more than welcome to create a PR.

**Comment by himelbrand** [comment]
can you please share your code?
I want to see what props you used

**Comment by himelbrand** [comment]
fixed the issue now, will be added to next version
