### ISSUE TITLE
if this.props.value is 0, inc and dec uses this.state.value, not this.props.value.

### ISSUE THREAD

**Issue by ks69** [himelbrand/react-native-numeric-input#2]
Hi. I use this plugin. So nice.

But I have an issue.
I created my form. It uses NumericInput.
And I set props.value=0 as init value when user change other param in my form.
inc and dec func in NumericInput.js check props.value as below.
"let value = this.props.value ? this.props.value : this.state.value"
It substitutions this.state.value for value cause this.props.value is 0.
e.g.
User clicked inc a few times. state.value is incremented.
Then User changed other param in my form.
I want to set value=0 to use props.value but value is incremented state.value.

For now, I changed as below.
"let value = (typeof this.props.value === 'number') ? this.props.value : this.state.value"

Is there any other way ?

Thank you.

**Comment by himelbrand** [comment]
Thank you for opening this issue,
it was fixed and be out on version 1.3.1

**Comment by ks69** [comment]
Thank you for your reply.
>and for offering a solution, next time you are welcome to make a pull request.
I'm sorry. I see.

Best regards.
