### ISSUE TITLE
seperatorWidth property spelling

### ISSUE THREAD

**Issue by jsuryahyd** [himelbrand/react-native-numeric-input#21]
Small Issue, but may cause some confusion, if not noticed by the users. 'seperatorWidth' property is spelled as 'sepratorWidth'(without 'e' after 'p'), so it works only when specified without the 'e'. 
Best solution might be to support the correct spelled property name, along with the present property name.

**Comment by himelbrand** [comment]
@jsuryahyd thanks for bringing to my attention.
I'm a little busy these days, you're welcome to make a PR with a fix,
else I'll get to it when I have the time.

**Comment by himelbrand** [comment]
#23 approved this PR 
with a fix.
bump version to 1.6.4 , now available via npm or yarn
