### ISSUE TITLE
How to pass dynamic value in the Input ?

### ISSUE THREAD

**Issue by KirankumarDafda** [himelbrand/react-native-numeric-input#25]
I am trying to add value direct from the API to FlatList, for eg. Cart screen with multiple item and multiple quantity, but it always render 0

**Comment by enriquehenriquezf** [comment]
with: `initValue={var}`

**Comment by himelbrand** [comment]
closing.
@enriquehenriquezf thanks for helping

**Comment by vikaskbh** [comment]
initValue is confusing. pls document it correctly to set dynamic value.
