### ISSUE TITLE
how to get value from react-native-numeric-input

### ISSUE THREAD

**Issue by ice16** [himelbrand/react-native-numeric-input#26]
How to get the data from numericInput. I want to get the result from the value I press
here is my code:
<NumericInput type='up-down'
							totalWidth={155} 
							totalHeight={40}
							value={this.state.value}							
							onChange={value =>console.log(value)} />

I have try 
<NumericInput  type='up-down' value={this.state.value} onChange={value => this.setState({value})}
 but this cannot work

**Comment by himelbrand** [comment]
@ice16 try as suggested here: https://github.com/himelbrand/react-native-numeric-input/issues/27#issuecomment-481616358
and I'll get to fixing this issue as soon as possible.
thanks for opening this issue

**Comment by himelbrand** [comment]
closed, also closed #27,
fix will be added next version
