### ISSUE TITLE
Value showed is not updated after change event

### ISSUE THREAD

**Issue by NDallaRiva** [himelbrand/react-native-numeric-input#27]
Hi,

I have this sample of code
```
<NumericInput 
                        minValue={0}
                        value={this.state.answers[index]}
                        onChange={value => {
                            console.log("$ ", this.state.answers[index])
                            let a = this.state.answers
                            a[index] = value
                            this.setState({answers: a})
                            console.log("$$$ ", this.state.answers[index])
                        }} 
                    />
```

What happens is

-  The console log with the single $ prints the current value
-  The console log with three $ prints the increased/decreased value
-  The component shows always the initial element (zero in my case)

**Comment by Super-Chama** [comment]
Had a similar issue and found that you need to initialize the component with 2 props as follows.
```
<NumericInput
  minValue={0}
  initValue={this.state.answers[index]} // Initial Value
  value={this.state.answers[index]} // Again the value prop, without this it will default to zero
  onChange={value => //do something}
 />
```
Good luck!

**Comment by Andyluchina** [comment]
> Had a similar issue and found that you need to initialize the component with 2 props as follows.
> 
> ```
> <NumericInput
>   minValue={0}
>   initValue={this.state.answers[index]} // Initial Value
>   value={this.state.answers[index]} // Again the value prop, without this it will default to zero
>   onChange={value => //do something}
>  />
> ```
> Good luck!

this is working. but it is laggy. probably because it renders the whole component.

**Comment by himelbrand** [comment]
@Andyluchina the lags you're talking about, they happen while js debugging is enabled?
