### ISSUE TITLE
Issue with real and int matches

### ISSUE THREAD

**Issue by stephaneraynaud-millevolts** [himelbrand/react-native-numeric-input#28]
https://github.com/himelbrand/react-native-numeric-input/blob/93f89b3a40da85838bf0afa6d7ae0cf68e0d69e3/NumericInput/NumericInput.js#L53

https://github.com/himelbrand/react-native-numeric-input/blob/93f89b3a40da85838bf0afa6d7ae0cf68e0d69e3/NumericInput/NumericInput.js#L65

Hello,

I think you inverted real and int match functions parameters.

Regards,
Stéphane

**Comment by himelbrand** [comment]
correct, thank you.
fixing it now
