### ISSUE TITLE
Need a prop that triggers when - / + is pressed after the quantity has reached min / max

### ISSUE THREAD

**Issue by sarahsga** [himelbrand/react-native-numeric-input#31]
**Desired Behaviour**: When min/max value is reached, clicking the - / + button should trigger a prop called incPressedAfterReachMax /  decPressedAfterReachMin, so the parent can show an alert message to the user accordingly.

**Current Behaviour**: When min/max value is reached and - / + buttons are clicked, there is no prop to inform the user about why the quantity no longer increments / decrements.

**Comment by himelbrand** [comment]
Hi @sarahsga ,
that's a good idea, I'll add it in the next version
