### ISSUE TITLE
how to set `iconStyle` props of two selector buttons when the value is same as `minValue` or `maxValue` props

### ISSUE THREAD

**Issue by achmadk** [himelbrand/react-native-numeric-input#6]
Hi, @himelbrand . Thanks for such an awesome library. I really appreciate it.

I would like to know how to set `iconStyle` props of two selector buttons when the `value` is same as `minValue` or `maxValue` props, so user seems that buttons is disabled.

Awaiting your response. Thanks in advance.

**Comment by himelbrand** [comment]
thank you for opening this issue,
currently i'm working on another project and doesn't have time right this moment to handle issues.
if you are able to fix the problem and create aPR it will be great, if not I'll try to get to it as soon as possible.

**Comment by himelbrand** [comment]
now uploading version 1.4.0,
@achmadk 
it will have the new feature you requested!
using the following props:
reachMaxIncIconStyle,    
reachMaxDecIconStyle,    
reachMinIncIconStyle,
reachMinDecIconStyle

all of these props are optional of course.

also updated docs
