### ISSUE TITLE
Issues with incrementing and decrementing decimal numbers

### ISSUE THREAD

**Issue by yogeshk19** [himelbrand/react-native-numeric-input#7]
Here is how we use the numeric input.

Min value = -40.0
Max Value = 135.0
step = 0.2
initValue and value = 98.6
```
<NumericInput 
                  minValue = {this.state.startTemp.min}
                   maxValue = {this.state.startTemp.max}
                   step={this.state.startTemp.step}
                   initValue={this.state.startTemp.currentValue}
                   value={this.state.startTemp.currentValue}
                    onChange={value => 
                              {
                                    this.setState(update(this.state, {
                                         startTemp: {
                                               currentValue: {$set: value}                                                
                                         }
                                    }))
                              }} 
                              totalWidth={calcSize(280)} 
                              totalHeight={calcSize(80)} 
                               iconSize={calcSize(50)}
                               valueType='real'
                               textColor='#B0228C' 
                               iconStyle={{ color: 'white' }} 
                               rightButtonBackgroundColor='#EA3788' 
                               leftButtonBackgroundColor='#E56B70'/>
```

1) Everything seems to work as I am incrementing but as soon as hit 99.4 and hit an increment the number that is shown in the text box has multiple decimal places and the ellipsis shows up with the text. I have in fact ensured that it stays a single decimal number.  

2) The same scenario when I decrement the number from 0 to say -40. I get way to many decimal places displayed. 

3) When i type in a number into the text box I can't enter a negative value. Since the minimum value in my case is -40.0

Please let me know if a fix is already available for this issue. Although I am using the latest react-native and the latest version of this repository as well.

Thanks,
Yogesh

**Comment by yogeshk19** [comment]
Debugging the code base, both the inc and dec functions in NumericInput.js, when incrementing/decrementing decimal number with a step which is also a decimal number results in a decimal number with multiple decimal places and the input text control ends up displaying a larger number. 
Easy way to reproduce this issue, set the initial value to 99.4 and increment it by 0.2, you will see a number with multiple decimal places and then immediately decrement the number and the number is reverted back to 99.4 with just 1 decimal place.

```
inc = () => {
        let value = this.props.value && (typeof this.props.value === 'number') ? this.props.value : this.state.value
        if (this.props.maxValue === null || (value < this.props.maxValue)) {
           //when the number is at 99.4 and incrementing 0.2 results in  a multiple decimal places.
          //after the code below the number of decimal places are increased.
           value += this.props.step
            this.setState({ value })
        }
        if (value !== this.props.value)
            this.props.onChange && this.props.onChange(value)

    }
```
Hope its an easy fix, I am not sure why certain numbers the component is incrementing/decrementing fine and most of them ending up with many decimal places.

Thanks,
Yogesh

**Comment by himelbrand** [comment]
thank you for opening this issue,
currently i'm working on another project and doesn't have time right this moment to handle issues.
if you are able to fix the problem and create aPR it will be great, if not I'll try to get to it as soon as possible.

**Comment by yogeshk19** [comment]
I was able to resolve it without any changes in the react native numeric-input component, I just curtailed it during the render while displaying the data using Number.toFixed() method. I am not sure if there needs to be a fix for this issue. Please close this issue at this point.

Thanks,
Yogesh

**Comment by Volekss** [comment]
@yogeshk19  can you please send me the snip code of your component? Still dealing with this issue.

**Comment by Volekss** [comment]
You can fix this simply by adding this

`dec = () => {
        let value = this.props.value && (typeof this.props.value === 'number') ? this.props.value : this.state.value
        if (this.props.minValue === null || (value > this.props.minValue)) {
            value -= this.props.step
            // added this line to fix the bug
            value = value.toFixed(2)

            this.setState({ value,stringValue:value.toString() })
        }`
