### ISSUE TITLE
[BUG] - I'm having an issue with adjusting icon size.

### ISSUE THREAD

**Issue by ErkanGorgulu** [himelbrand/react-native-numeric-input#71]
No matter what i tried i can't get the correct icon size for my design. I am trying to apply design on the image i added.
![Ekran Alıntısı](https://user-images.githubusercontent.com/16388246/96714329-aa738e80-13aa-11eb-82d1-419868e83c81.PNG)

**Comment by karanzijm** [comment]
@ErkanGorgulu have u tried adjusting the totalWidth or totalHeight?
