### ISSUE TITLE
Can't type in negative number

### ISSUE THREAD

**Issue by ericag1985** [himelbrand/react-native-numeric-input#8]
If I hit the `-` button, the input works fine, but if I try to type in a negative number it does not allow it.

**Comment by himelbrand** [comment]
thank you for opening this issue,
currently i'm working on another project and doesn't have time right this moment to handle issues.
if you are able to fix the problem and create aPR it will be great, if not I'll try to get to it as soon as possible.

**Comment by himelbrand** [comment]
im fixing this issue right now

**Comment by himelbrand** [comment]
fixed on version 1.3.2
