### ISSUE TITLE
Change input from keyboard

### ISSUE THREAD

**Issue by yoyq** [himelbrand/react-native-numeric-input#9]
Hi,

How can I change input from keyboard and after this check min and max value?

Example: min value = 10, max value = 100, value = 50
If I add from keyboard any number or delete number current value don't show and show the last value. I want to clear value only after removing focus from input.

Thanks in advance!

**Comment by himelbrand** [comment]
thank you for opening this issue,
currently i'm working on another project and doesn't have time right this moment to handle issues.
if you are able to fix the problem and create aPR it will be great, if not I'll try to get to it as soon as possible.

**Comment by zedtux** [comment]
+1 I'm also looking for this

**Comment by himelbrand** [comment]
working on the fix now

**Comment by himelbrand** [comment]
fixed on version 1.3.2

**Comment by zedtux** [comment]
Thank you @himelbrand.
